### ISSUE TITLE
Access duration of and number of players of games

### ISSUE THREAD

**Issue by jschouwstra** [rsahlstrom/shelf#11]
Hi Janiv, 
first off, thanks a lot for making the package to access the bgg API in an easier way!
I have a question rather than an issue, is there a way to get the duration and number of players for the specified game?

![screenshot_4](https://user-images.githubusercontent.com/10322841/29568684-6faf6ea6-8751-11e7-8efd-a90bdba94b65.png)

**Comment by rsahlstrom** [comment]
Here's an example XML:

https://www.boardgamegeek.com/xmlapi2/thing?id=13

You can see in there we have minplayers and maxplayers. We also have minplaytime and maxplaytime.

To get this data from your game entity, you can call `$game->getMinPlayers()` or `$game->getMaxPlayers()` as well as `$game->getMinPlayTime()` or `$game->getMaxPlayTime()`.
